### PR TITLE
feat: add extensive_parameters in tke endpoint resource

### PR DESCRIPTION
**Pull request by xawei**

### CODE REVIEW

**Comment by lyu571** [comment]
用例名需要更新。
没有匹配上，e2e实际上没有跑。
image

**Comment by xawei** [comment]
> 提供一下本地e2e pass的截图哈。

企业微信截图_0a90f17d-3d3a-4654-8beb-91af5f25b99e

**Review by lyu571 — APPROVED** [review]
LGTM.

**Comment by lyu571** [comment]
This PR has passed local e2e testing. It can be merged, although existing an e2e failed case caused by a tf known issue.

**Pull request merged**
